//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VistasSorrySliders.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VistasSorrySliders.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BUSCAR.
        /// </summary>
        public static string btnBuscar {
            get {
                return ResourceManager.GetString("btnBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANCELAR.
        /// </summary>
        public static string btnCancelar {
            get {
                return ResourceManager.GetString("btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTINUAR.
        /// </summary>
        public static string btnContinuar {
            get {
                return ResourceManager.GetString("btnContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTINUAR COMO INVITADO.
        /// </summary>
        public static string btnContinuarInvitado {
            get {
                return ResourceManager.GetString("btnContinuarInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREAR CUENTA.
        /// </summary>
        public static string btnCrearCuenta {
            get {
                return ResourceManager.GetString("btnCrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C R E A R   L O B B Y.
        /// </summary>
        public static string btnCrearLobby {
            get {
                return ResourceManager.GetString("btnCrearLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENVIAR CÓDIGO.
        /// </summary>
        public static string btnEnviarCodigo {
            get {
                return ResourceManager.GetString("btnEnviarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR CAMBIOS.
        /// </summary>
        public static string btnGuardarCambios {
            get {
                return ResourceManager.GetString("btnGuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I N I C I A R   P A R T I D A.
        /// </summary>
        public static string btnIniciarPartida {
            get {
                return ResourceManager.GetString("btnIniciarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REGISTRAR CUENTA.
        /// </summary>
        public static string btnRegistrarCuenta {
            get {
                return ResourceManager.GetString("btnRegistrarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SALIR.
        /// </summary>
        public static string btnSalir {
            get {
                return ResourceManager.GetString("btnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UNIRSE A LA PARTIDA.
        /// </summary>
        public static string btnUnirsePartida {
            get {
                return ResourceManager.GetString("btnUnirsePartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustes.
        /// </summary>
        public static string lblAjustes {
            get {
                return ResourceManager.GetString("lblAjustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido/s.
        /// </summary>
        public static string lblApellidos {
            get {
                return ResourceManager.GetString("lblApellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avatar.
        /// </summary>
        public static string lblAvatar {
            get {
                return ResourceManager.GetString("lblAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        public static string lblBienvenido {
            get {
                return ResourceManager.GetString("lblBienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido de nuevo.
        /// </summary>
        public static string lblBienvenidoNuevo {
            get {
                return ResourceManager.GetString("lblBienvenidoNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de partida:.
        /// </summary>
        public static string lblCodigoPartida {
            get {
                return ResourceManager.GetString("lblCodigoPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        public static string lblContrasena {
            get {
                return ResourceManager.GetString("lblContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo:.
        /// </summary>
        public static string lblCorreo {
            get {
                return ResourceManager.GetString("lblCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string lblCorreoElectronico {
            get {
                return ResourceManager.GetString("lblCorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo de Jugador sin Cuenta:.
        /// </summary>
        public static string lblCorreoJugadorSinCuenta {
            get {
                return ResourceManager.GetString("lblCorreoJugadorSinCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4 Jugadores.
        /// </summary>
        public static string lblCuatroJugadores {
            get {
                return ResourceManager.GetString("lblCuatroJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de la cuenta.
        /// </summary>
        public static string lblDatosCuenta {
            get {
                return ResourceManager.GetString("lblDatosCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2 Jugadores.
        /// </summary>
        public static string lblDosJugadores {
            get {
                return ResourceManager.GetString("lblDosJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string lblEspanol {
            get {
                return ResourceManager.GetString("lblEspanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host de la Partida:.
        /// </summary>
        public static string lblHostPartida {
            get {
                return ResourceManager.GetString("lblHostPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IDIOMA:.
        /// </summary>
        public static string lblIdioma {
            get {
                return ResourceManager.GetString("lblIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string lblIngles {
            get {
                return ResourceManager.GetString("lblIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIAR SESIÓN.
        /// </summary>
        public static string lblInicioSesion {
            get {
                return ResourceManager.GetString("lblInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INVITAR JUGADOR.
        /// </summary>
        public static string lblInvitarJugador {
            get {
                return ResourceManager.GetString("lblInvitarJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de amigos.
        /// </summary>
        public static string lblListaAmigos {
            get {
                return ResourceManager.GetString("lblListaAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de jugadores.
        /// </summary>
        public static string lblListaDeJugadores {
            get {
                return ResourceManager.GetString("lblListaDeJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LOBBY DE ESPERA.
        /// </summary>
        public static string lblLobbyEspera {
            get {
                return ResourceManager.GetString("lblLobbyEspera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modo de Juego Normal.
        /// </summary>
        public static string lblModoJuego {
            get {
                return ResourceManager.GetString("lblModoJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname/apodo.
        /// </summary>
        public static string lblNickname {
            get {
                return ResourceManager.GetString("lblNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre/s.
        /// </summary>
        public static string lblNombres {
            get {
                return ResourceManager.GetString("lblNombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TABLERO DE PUNTUACIONES.
        /// </summary>
        public static string lblTablaPuntuaciones {
            get {
                return ResourceManager.GetString("lblTablaPuntuaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de Jugadores:.
        /// </summary>
        public static string lblTotalJugadores {
            get {
                return ResourceManager.GetString("lblTotalJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3 Jugadores.
        /// </summary>
        public static string lblTresJugadores {
            get {
                return ResourceManager.GetString("lblTresJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UNIRSE A PARTIDA.
        /// </summary>
        public static string lblUnirsePartida {
            get {
                return ResourceManager.GetString("lblUnirsePartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo ingresado se encuentra registrado en el sistema.
        /// </summary>
        public static string msgCorreoEncontrado {
            get {
                return ResourceManager.GetString("msgCorreoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico es inválido, ingresa una dirección valida.
        /// </summary>
        public static string msgCorreoInvalido {
            get {
                return ResourceManager.GetString("msgCorreoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta se ha registrado exitosamente.
        /// </summary>
        public static string msgCuentaCreada {
            get {
                return ResourceManager.GetString("msgCuentaCreada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar la imagen del avatar por defecto.
        /// </summary>
        public static string msgErrorAvatarDefault {
            get {
                return ResourceManager.GetString("msgErrorAvatarDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error de conexión con la base de datos.
        /// </summary>
        public static string msgErrorBaseDatos {
            get {
                return ResourceManager.GetString("msgErrorBaseDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error de conexión con el servidor.
        /// </summary>
        public static string msgErrorConexion {
            get {
                return ResourceManager.GetString("msgErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contar con: Mínimo 8 caracteres, con un número o un carácter especial.
        /// </summary>
        public static string msgErrorContrasenaInvalida {
            get {
                return ResourceManager.GetString("msgErrorContrasenaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La imagen no se puede cargar.
        /// </summary>
        public static string msgErrorImagen {
            get {
                return ResourceManager.GetString("msgErrorImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se tienen permisos para acceder al archivo.
        /// </summary>
        public static string msgErrorImagenPermisos {
            get {
                return ResourceManager.GetString("msgErrorImagenPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La imagen supera el límite de 400 KB.
        /// </summary>
        public static string msgErrorTamañoImagen {
            get {
                return ResourceManager.GetString("msgErrorTamañoImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin permisos para el archivo.
        /// </summary>
        public static string msgErrorTituloImagenPermisos {
            get {
                return ResourceManager.GetString("msgErrorTituloImagenPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, seleccione un archivo de imagen válida.
        /// </summary>
        public static string msgImagenInvalida {
            get {
                return ResourceManager.GetString("msgImagenInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aun no hay ganadores, Sé el primero en ganar.
        /// </summary>
        public static string msgTablaVacia {
            get {
                return ResourceManager.GetString("msgTablaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La imagen supera el limite de 400KB.
        /// </summary>
        public static string msgTamañoImagenError {
            get {
                return ResourceManager.GetString("msgTamañoImagenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña invalida.
        /// </summary>
        public static string msgTituloContraseñaInvalida {
            get {
                return ResourceManager.GetString("msgTituloContraseñaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta previamente registrada.
        /// </summary>
        public static string msgTituloCorreoEncontrado {
            get {
                return ResourceManager.GetString("msgTituloCorreoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo invalido.
        /// </summary>
        public static string msgTituloCorreoInvalido {
            get {
                return ResourceManager.GetString("msgTituloCorreoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta creada.
        /// </summary>
        public static string msgTituloCuentaCreada {
            get {
                return ResourceManager.GetString("msgTituloCuentaCreada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar la imagen.
        /// </summary>
        public static string msgTituloErrorAvatarDefault {
            get {
                return ResourceManager.GetString("msgTituloErrorAvatarDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de imagen.
        /// </summary>
        public static string msgTituloErrorImagen {
            get {
                return ResourceManager.GetString("msgTituloErrorImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen demasiado grande.
        /// </summary>
        public static string msgTituloErrorTamañoImagen {
            get {
                return ResourceManager.GetString("msgTituloErrorTamañoImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen demasiado grande.
        /// </summary>
        public static string msgTituloTamañoImagenError {
            get {
                return ResourceManager.GetString("msgTituloTamañoImagenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivos de imagen.
        /// </summary>
        public static string strArchivosImagen {
            get {
                return ResourceManager.GetString("strArchivosImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AJUSTES.
        /// </summary>
        public static string txtBlockAjustes {
            get {
                return ResourceManager.GetString("txtBlockAjustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código no válido.
        /// </summary>
        public static string txtBlockCodigoNoValido {
            get {
                return ResourceManager.GetString("txtBlockCodigoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONFIGURAR PARTIDA.
        /// </summary>
        public static string txtBlockConfigurarPartida {
            get {
                return ResourceManager.GetString("txtBlockConfigurarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no es correcta. Verifica tu contraseña e inténtalo de nuevo.
        /// </summary>
        public static string txtBlockContrasenaInvalida {
            get {
                return ResourceManager.GetString("txtBlockContrasenaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico no se encuentra registrado en el sistema.
        /// </summary>
        public static string txtBlockCorreoInvalido {
            get {
                return ResourceManager.GetString("txtBlockCorreoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREAR LOBBY.
        /// </summary>
        public static string txtBlockCrearLobby {
            get {
                return ResourceManager.GetString("txtBlockCrearLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su cuenta ya está jugando dentro del lobby.
        /// </summary>
        public static string txtBlockCuentaYaEnLobby {
            get {
                return ResourceManager.GetString("txtBlockCuentaYaEnLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JUGADORES Y AMIGOS.
        /// </summary>
        public static string txtBlockJugadoresAmigos {
            get {
                return ResourceManager.GetString("txtBlockJugadoresAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida no acepta más jugadores.
        /// </summary>
        public static string txtBlockJugadoresMaximosExcedidos {
            get {
                return ResourceManager.GetString("txtBlockJugadoresMaximosExcedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NICKNAME/APODO.
        /// </summary>
        public static string txtBlockNickname {
            get {
                return ResourceManager.GetString("txtBlockNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname no es válido.
        /// </summary>
        public static string txtBlockNicknameNoValido {
            get {
                return ResourceManager.GetString("txtBlockNicknameNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RONDAS GANADAS.
        /// </summary>
        public static string txtBlockRondasGanadas {
            get {
                return ResourceManager.GetString("txtBlockRondasGanadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TABLA DE PUNTUACIONES.
        /// </summary>
        public static string txtBlockTablaPuntuaciones {
            get {
                return ResourceManager.GetString("txtBlockTablaPuntuaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UNIRSE A PARTIDA.
        /// </summary>
        public static string txtBlockUnirsePartida {
            get {
                return ResourceManager.GetString("txtBlockUnirsePartida", resourceCulture);
            }
        }
    }
}
